### ISSUE TITLE
Milestone v1.0.0

### ISSUE THREAD

**Issue by chenasraf** [chenasraf/ctelnet_dart#2]
These are main things I am planning to include before v1.0.0.

This issue will be used to track the progress. Please feel free to post feedback/ideas.

### Must have

- [ ] Tests for all features
- [x] Improve connection flow
   - `connect()` should complete on successful connection, throw on failure
   - Make sure `dispose()` is being called properly
   - Possibly use a `Stream` to listen to incoming data instead of using the constructor (allows for more flexibility with handling incoming/outgoing data)
- [ ] GitHub Actions Test & Build (possibly publish?)

## Ideas
- [x] Color parser
   I have a working tokenizer for colors. With some improvements, it could be included to allow parsing terminal colors. I am not sure whether it should be within the scope of this package (maybe another one?)
